export const apiConfig = {
  filiere: "http://localhost:8066/api/filieres",
  niveau: "http://localhost:8066/api/niveaux",
  specialite: "http://localhost:8066/api/specialites",
  matiere: "http://localhost:8066/api/matieres",
  etudiant: "http://localhost:8066/api/etudiants",
  rembourssement: "http://localhost:8072/api/rembour",
  interet: "http://localhost:8072/interets",
  notificationPreference: "http://localhost:8066/api/notifications/preferences",
  generateDocument: "http://localhost:8088/api/generateDocument",
  statistic: "http://localhost:8072/api/Statistique",
  empruntExport: "http://localhost:8067/api/rapports",
  configuration: "http://localhost:8088/api/configurations",
  remboursementExport: "http://localhost:8072/api/rapports",
  fonctionBureau: "http://localhost:8066/api/fonctions-bureau",
  user: "http://localhost:8066/users",
  role: "http://localhost:8066/roles",
  auth: "http://localhost:8066/api/auth",
};
